# Generated by Django 6.0.4 on 2026-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Primary contact's full name", max_length=255, verbose_name='Full Name')),
                ('company', models.CharField(blank=True, default='', help_text='Client organization name', max_length=255, verbose_name='Company / Organization')),
                ('corporate_email', models.EmailField(help_text='Official business email address', max_length=254, verbose_name='Corporate Email')),
                ('phone', models.CharField(blank=True, default='', help_text='Contact telephone number with country code', max_length=50, verbose_name='Phone Number')),
                ('discipline', models.CharField(blank=True, default='', help_text='e.g. HVAC & Cleanroom Engineering, Process Engineering, etc.', max_length=150, verbose_name='Engineering Discipline')),
                ('project_scope', models.TextField(help_text='Facility requirements, cleanroom classification, timeline, regulatory targets, etc.', verbose_name='Project Scope')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', help_text='Workflow status (new, contacted, closed)', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when enquiry was recorded', verbose_name='Created At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client submitting the form', null=True, verbose_name='Client IP Address')),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': 'Project Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
